apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cognee
  labels:
    app: {{ .Release.Name }}-cognee
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cognee.port }}
      targetPort: {{ .Values.cognee.port }}
  selector:
    app: {{ .Release.Name }}-cognee
