# Configuration for the 'cognee' application service
cognee:
  # Image name (using the local image weâ€™ll build in Minikube)
  image: "cognee/cognee:main"
  port: 8000
  env:
    HOST: "0.0.0.0"
    ENVIRONMENT: "local"
    PYTHONPATH: "."
    LLM_MODEL: "openai/gpt-4o-mini"
    LLM_PROVIDER: "openai"
  resources:
    cpu: "4.0"
    memory: "2Gi"

# Configuration for the 'postgres' database service
postgres:
  image: "pgvector/pgvector:pg17"
  port: 5432
  env:
    POSTGRES_USER: "cognee"
    POSTGRES_PASSWORD: "cognee"
    POSTGRES_DB: "cognee_db"
  storage: "2Gi"
