# Long-running, heavy and resource-consuming tests for release validation
name: Release Test Workflow

permissions:
  contents: read

on:
  push:
    branches:
      - feature/cog-3213-docs-set-up-guide-script-tests
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  load-tests:
    name: Load Tests
    uses: ./.github/workflows/load_tests.yml
    secrets: inherit

