# Long-running, heavy and resource-consuming tests for release validation
name: Release Test Workflow

permissions:
  contents: read

on:
  push:
    branches:
      - feature/cog-3213-docs-set-up-guide-script-tests
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
#  load-tests:
#    name: Load Tests
#    uses: ./.github/workflows/load_tests.yml
#    secrets: inherit

  docs-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger docs tests
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DOCS_REPO_PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/topoteretes/cognee-docs/dispatches \
            -d '{"event_type":"new-main-release","client_payload":{"caller_repo":"'"${GITHUB_REPOSITORY}"'"}}'
