name: test | mcp

on:
  workflow_call:
    inputs:
      cognee_version:
        required: false
        type: string
        default: "local" # local - Installing Cognee from local source
        description: "Pypi-compatible version of cognee to use. For example, 0.5.2.dev0. `local` (default) - Installing Cognee from local source"
jobs:
  test-mcp:
    name: Run MCP Test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install UV
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies
        shell: bash
        working-directory: cognee-mcp
        run: uv sync

      - name: (Re)Install Cognee
        shell: bash
        working-directory: cognee-mcp
        run: |
          uv pip uninstall cognee
          if [ "${{ inputs.cognee_version }}" = "local" ]; then
            echo "Installing Cognee from local source ..."
            uv pip install --force-reinstall -e ../
          else
            echo "Installing Cognee version ${{ inputs.cognee_version }} from PyPI..."
            uv pip install --force-reinstall "cognee==${{ inputs.cognee_version }}"
          fi

      - name: Run MCP test
        env:
          ENV: 'dev'
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
          LLM_ENDPOINT: ${{ secrets.LLM_ENDPOINT }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_API_VERSION: ${{ secrets.LLM_API_VERSION }}
          EMBEDDING_DIMENSIONS: 300
          EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
          EMBEDDING_ENDPOINT: ${{ secrets.EMBEDDING_ENDPOINT }}
          EMBEDDING_API_KEY: ${{ secrets.EMBEDDING_API_KEY }}
          EMBEDDING_API_VERSION: ${{ secrets.EMBEDDING_API_VERSION }}
        working-directory: cognee-mcp
        run: |
          echo "Cognee Version:"
          uv pip show cognee | grep Version
          uv run --no-sync python ./src/test_client.py
