name: test | code graph example

on:
  workflow_call:
    secrets:
      inherit: true
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  run_simple_example_test:
      uses: ./.github/workflows/reusable_python_example.yml
      with:
        example-location: ./examples/python/code_graph_example.py
        arguments: "--repo_path ./cognee/tasks/graph"
      secrets:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LLM_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GRAPHISTRY_USERNAME: ${{ secrets.GRAPHISTRY_USERNAME }}
        GRAPHISTRY_PASSWORD: ${{ secrets.GRAPHISTRY_PASSWORD }}
