name: test | gemini

on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_simple_example_test:
      uses: ./.github/workflows/reusable_python_example.yml
      with:
        example-location: ./examples/python/simple_example.py
      secrets:
        GRAPHISTRY_USERNAME: ${{ secrets.GRAPHISTRY_USERNAME }}
        GRAPHISTRY_PASSWORD: ${{ secrets.GRAPHISTRY_PASSWORD }}
        EMBEDDING_PROVIDER: "gemini"
        EMBEDDING_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        EMBEDDING_MODEL: "gemini/text-embedding-004"
        EMBEDDING_ENDPOINT: "https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004"
        EMBEDDING_API_VERSION: "v1beta"
        EMBEDDING_DIMENSIONS: "768"
        EMBEDDING_MAX_TOKENS: "8076"
        LLM_PROVIDER: "gemini"
        LLM_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        LLM_MODEL: "gemini/gemini-1.5-flash"
        LLM_ENDPOINT: "https://generativelanguage.googleapis.com/"
        LLM_API_VERSION: "v1beta"
