name: test | chromadb

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUNTIME__LOG_LEVEL: ERROR

jobs:
  run_chromadb_integration_test:
    name: chromadb test
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    services:
      chromadb:
        image: chromadb/chroma:0.6.3
        env:
          IS_PERSISTENT: TRUE
          CHROMA_SERVER_AUTH_PROVIDER: chromadb.auth.token.TokenAuthServerProvider
          CHROMA_SERVER_AUTH_CREDENTIALS: test-token
          CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER: chromadb.auth.token.TokenConfigServerAuthCredentialsProvider
          CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER: AUTHORIZATION
        options: >-
          --health-cmd "cat < /dev/null > /dev/tcp/localhost/8000"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 3
          --volume $(pwd)/.chromadb_data/:/chroma/chroma/
        ports:
          - 3002:8000

    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run chromadb test
        env:
          ENV: 'dev'
          VECTOR_DB_PROVIDER: chromadb
          VECTOR_DB_URL: http://localhost:3002
          VECTOR_DB_KEY: test-token
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
          LLM_ENDPOINT: ${{ secrets.LLM_ENDPOINT }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_API_VERSION: ${{ secrets.LLM_API_VERSION }}
          EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
          EMBEDDING_ENDPOINT: ${{ secrets.EMBEDDING_ENDPOINT }}
          EMBEDDING_API_KEY: ${{ secrets.EMBEDDING_API_KEY }}
          EMBEDDING_API_VERSION: ${{ secrets.EMBEDDING_API_VERSION }}
        run: poetry run python ./cognee/tests/test_chromadb.py
