name: test | code graph example

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, synchronize]


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_simple_example_test:
      uses: ./.github/workflows/reusable_python_example.yml
      with:
        example-location: ./examples/python/code_graph_example.py
        arguments: "--repo_path ./evals"
      secrets:
        LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}
        LLM_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        EMBEDDING_PROVIDER: ${{ secrets.EMBEDDING_PROVIDER }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GRAPHISTRY_USERNAME: ${{ secrets.GRAPHISTRY_USERNAME }}
        GRAPHISTRY_PASSWORD: ${{ secrets.GRAPHISTRY_PASSWORD }}
